import iconStyles from './style.module.scss';
    
export const IconVariant = {
    IconAccountHand: iconStyles['icon-account-hand'],
    IconAlienArrow: iconStyles['icon-alien-arrow'],
    IconArrowRight: iconStyles['icon-arrow-right'],
    IconBank: iconStyles['icon-bank'],
    IconBookmark: iconStyles['icon-bookmark'],
    IconBulb: iconStyles['icon-bulb'],
    IconCar: iconStyles['icon-car'],
    IconCard: iconStyles['icon-card'],
    IconCart: iconStyles['icon-cart'],
    IconChart: iconStyles['icon-chart'],
    IconChip: iconStyles['icon-chip'],
    IconCoins: iconStyles['icon-coins'],
    IconConnectedDots: iconStyles['icon-connected-dots'],
    IconCurlyArrow: iconStyles['icon-curly-arrow'],
    IconGroup: iconStyles['icon-group'],
    IconGrowingChart: iconStyles['icon-growing-chart'],
    IconHeartDiagram: iconStyles['icon-heart-diagram'],
    IconHeartHand: iconStyles['icon-heart-hand'],
    IconKey: iconStyles['icon-key'],
    IconLock: iconStyles['icon-lock'],
    IconPen: iconStyles['icon-pen'],
    IconRecicle: iconStyles['icon-recicle'],
    IconSafe: iconStyles['icon-safe'],
    IconSignal: iconStyles['icon-signal'],
    IconSimpleCart: iconStyles['icon-simple-cart'],
    IconSquare: iconStyles['icon-square'],
    IconSquares: iconStyles['icon-squares'],
    IconTorch: iconStyles['icon-torch'],
    IconTriangle: iconStyles['icon-triangle'],
    IconTv: iconStyles['icon-tv'],
    IconWaypoint: iconStyles['icon-waypoint'],
    IconWorldWideVideo: iconStyles['icon-world-wide-video'],
    IconWorldWide: iconStyles['icon-world-wide'],
}