define([], function() {
  return {
    Title: 'Link title',
    Text: 'Link text',
    LinkText: 'Link text',
    ImageUrl: 'Link image URL',
    Target: 'Open in current tab?',
    TargetOn: 'Open link in the current tab',
    TargetOff: 'Open link in a new tab',
    NumberOfLinks: 'Number of links',
    ExternalLink: 'External link',
    URL: 'Link URL',
    Variant: 'Link style',
    LinkGroupName: 'Link',
    CommonLinkConfig: 'Common Link config',
    InternalSiteLink: 'Internal link',
    SectionDescription: 'Link set configuration',
    bordered: 'Outline button',
    background: 'Background button',
    ghostArrowRight: 'Ghost button',
    ghostArrowLeft: 'Curly arrow button',
    verticalBlock: 'Vertical button',
    WhiteText: 'Make text white?',
    Yes: 'Yes',
    No: 'No',
    RemoveLink: 'Remove',
  }
});
