define([], function() {
  return {
    Title: "Card title",
    Text:"Card description",
    LinkText: "Link text",
    ImageUrl: "Image URL",
    Target: "Open in current tab?",
    NumberOfTiles: "Number of cards",
    InternalLink: "Internal link",
    URL: "Card URL",
    LinkURL: "Link URL",
    Variant: "Card style",
    bordered: "Outline",
    backround: "Fill color",
    ghostArowRight: "Right Arrow",
    ghostArowLeft: "Left Arrow",
    vertcalBlock: "Vertical Buttons",
    TileGroupName: "Card",
    CommonCardConfig: "Common Card configuration",
    TargetOn: 'Open link in the current tab',
    TargetOff: 'Open link in a new tab',
    ArrowCard: 'Arrow card',
    IconCard: 'Icon card',
    TextCard: 'Text card',
    BlogPostCard: 'Blog post card',
    ThreeColumnsLabel: 'Use it in 3 columns?',
    Yes: 'Yes',
    No: 'No',
    RemoveCard: 'Remove',
  }
});
