name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:      
  publish:
      runs-on: ubuntu-latest
  
      strategy:
        matrix:
          node-version: [16.13.0]

      steps:
        - uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Build
          continue-on-error: true
          run: |
            npm install -g yarn@1.22.19
            yarn
            yarn global add yo@3.0.0 gulp@4.0.2
            gulp clean
            gulp trust-dev-cert
            gulp bundle --ship
            gulp package-solution --ship
        
        - uses: zattoo/publish@v1
          with:
            github_token: ${{github.token}}
            sources: './sharepoint/solution/sp-component-solution.sppkg'
